version: "3.6"
services:
  nginx:
    image: makeitokay/digital_diary_nginx:latest
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/digitaldiary.site:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - digital_diary
      - digital_diary_admin
      - client
  digital_diary_admin:
    image: makeitokay/digital_diary_admin:latest
    build:
      context: .
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DIGITAL_DIARY_Email:Password=${EMAIL_PASSWORD}
      - DIGITAL_DIARY_ConnectionStrings:Default=User ID=digitaldiary;Password=${POSTGRES_PASSWORD};Server=188.120.245.245;Port=5432;Database=digitaldiary;Pooling=true;
  digital_diary:
    image: makeitokay/digital_diary:latest
    build:
      context: .
      target: DigitalDiary
    environment:
      - DOTNET_ENVIRONMENT=Production
      - DIGITAL_DIARY_Email:Password=${EMAIL_PASSWORD}
      - DIGITAL_DIARY_ConnectionStrings:Default=User ID=digitaldiary;Password=${POSTGRES_PASSWORD};Server=188.120.245.245;Port=5432;Database=digitaldiary;Pooling=true;
  client:
    image: makeitokay/digital_diary_client:latest
    build:
      context: client
    environment:
      - REACT_APP_API_BASE_URL=https://api.digitaldiary.site